/**
 * `@specra/release`: the immutable documentation release contracts of
 * SPEC-010. Pure data logic over the canonical and content artifacts:
 * version identifiers, the release manifest and catalog, the canonical
 * versioned route table, validated internal redirects, structured
 * contract-diff candidates, and the human-reviewed changelog. Filesystem
 * work (staging, atomic promotion, locking) lives in the CLI; serving lives
 * in the reader.
 */
export {
  CANDIDATES_DIRECTORY,
  CATALOG_FILENAME,
  CATALOG_FORMAT_VERSION,
  findRelease,
  MAX_RETAINED_RELEASES,
  parseReleaseCatalog,
  parseReleaseCatalogValue,
  RELEASES_DIRECTORY,
  selectorOrder,
  serializeReleaseCatalog,
  type CatalogRelease,
  type ReleaseCatalog,
  type ReleaseState,
} from "./catalog.js";
export {
  CHANGELOG_FILENAME,
  CHANGELOG_FORMAT_VERSION,
  CHANGELOG_ITEM_KINDS,
  CHANGELOG_MESSAGES,
  CHANGELOG_SOURCE_DIRECTORY,
  MAX_CHANGELOG_ENTRIES,
  MAX_CHANGELOG_ITEMS,
  MAX_CHANGELOG_SOURCE_BYTES,
  parseChangelog,
  parseChangelogSource,
  serializeChangelog,
  validateChangelog,
  type ChangelogDiagnostic,
  type ChangelogDiagnosticCode,
  type ChangelogEntry,
  type ChangelogItem,
  type ChangelogItemKind,
  type ChangelogSource,
  type ChangelogSourceEntry,
  type ChangelogSourceItem,
  type ChangelogValidation,
  type ChangelogValidationInput,
  type OperationLookup,
  type PublishedChangelog,
} from "./changelog.js";
export {
  DIFF_CANDIDATES_FILENAME,
  DIFF_FORMAT_VERSION,
  diffArtifacts,
  MAX_CHANGES_PER_CANDIDATE,
  MAX_DIFF_CANDIDATES,
  serializeContractDiff,
  type CandidateChange,
  type CandidateKind,
  type ChangeAspect,
  type ContractDiff,
  type DiffCandidate,
  type DiffInput,
  type DiffOptions,
} from "./diff.js";
export {
  computeReleaseDigest,
  createReleaseManifest,
  parseReleaseManifest,
  parseReleaseManifestValue,
  RELEASE_COMPONENT_NAMES,
  RELEASE_FORMAT_VERSION,
  RELEASE_MANIFEST_FILENAME,
  ReleaseContractError,
  serializeReleaseManifest,
  sha256Of,
  type ReleaseAsset,
  type ReleaseComponent,
  type ReleaseComponentName,
  type ReleaseManifest,
} from "./manifest.js";
export {
  ALIAS_REDIRECT_STATUS,
  isInternalRedirectPath,
  MAX_REDIRECTS,
  MIGRATION_REDIRECT_STATUS,
  parseRedirectTable,
  REDIRECT_MESSAGES,
  REDIRECTS_FILENAME,
  REDIRECTS_FORMAT_VERSION,
  serializeRedirectTable,
  validateRedirects,
  type RedirectDiagnostic,
  type RedirectDiagnosticCode,
  type RedirectEntry,
  type RedirectInput,
  type RedirectTable,
  type RedirectValidation,
} from "./redirects.js";
export {
  deriveRouteTable,
  findCounterpart,
  findRoute,
  MAX_ROUTES,
  parseRouteTable,
  ROUTES_FILENAME,
  ROUTES_FORMAT_VERSION,
  scopeRoute,
  serializeRouteTable,
  versionRoots,
  type ReleaseRoute,
  type RouteKind,
  type RouteTable,
  type RouteTableInput,
  type VersionRoots,
} from "./routes.js";
export {
  isVersionId,
  MAX_VERSION_ID_LENGTH,
  RESERVED_VERSION_IDS,
  validateVersionId,
  VERSION_ID_MESSAGES,
  versionKey,
  type VersionIdIssue,
} from "./version.js";
